### ISSUE TITLE
`filename` should be `fileName`

### ISSUE THREAD

**Issue by MatthijsKamstra** [Orange-hx/hxneu#1]
https://github.com/Orange-hx/hxneu/blob/04b77f1beac25755061ece24e6e99733c65984c8/src/Neutralino.hx#L160

`filename` should be `fileName`

https://neutralino.js.org/docs/api/filesystem#readfileoptions

**Comment by Rabios** [comment]
@MatthijsKamstra Sorry for late reply, Will fix this ASAP...

Will keep issue open untio the fix, Thanks!

**Comment by MatthijsKamstra** [comment]
I could have done it myself (pull request, etc)... so I am not in a hurry, and don't want to assume anything about how you should use your time..... 

it was a small adjustment, to keep the repos in sync with eachother

**Comment by Rabios** [comment]
@MatthijsKamstra Fixed! Thanks! ❤️
